ALTER TYPE "TipoDocumento" ADD VALUE IF NOT EXISTS 'CONSENTIMIENTO_ANESTESIA';
ALTER TYPE "TipoDocumento" ADD VALUE IF NOT EXISTS 'AUTORIZACION_QX';
ALTER TYPE "TipoDocumento" ADD VALUE IF NOT EXISTS 'HISTORIA_CLINICA';
ALTER TYPE "TipoDocumento" ADD VALUE IF NOT EXISTS 'NOTA_EVOLUCION';
ALTER TYPE "TipoDocumento" ADD VALUE IF NOT EXISTS 'NOTA_QUIRURGICA';
